# Risk Management
max_portfolio_risk: 0.02
max_position_risk: 0.01
max_position_pct: 0.1

# Trading Parameters
confidence_threshold: 0.4
rebalance_frequency: 1h
min_data_points: 50

# API Settings
alpaca_paper_trading: true
binance_testnet: true
max_retries: 3
retry_delay: 5.0

# Strategy Weights (must sum to 1.0)
default_strategy_weights:
  momentum_breakout: 0.4
  mean_reversion: 0.3
  ml_strategy: 0.3

# Assets to analyze
stock_universe:
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - TSLA
  - META
  - NVDA
  - BRK.B
  - JNJ
  - V
crypto_universe:
  - BTC/USDT
  - ETH/USDT
  - SOL/USDT
  - ADA/USDT
  - DOT/USDT
  - AVAX/USDT
  - ALGO/USDT

# Notification Settings
enable_notifications: true
notification_channels:
  - telegram
  - email

# Machine Learning Settings
ml_retrain_hours: 24
ml_min_samples: 100
ml_feature_selection: true
ml_ensemble_models: true

# Performance Settings
max_concurrent_assets: 10
data_cache_hours: 1
enable_performance_monitoring: true

# Live trading settings
poll_interval_seconds: 60

# Halal screening thresholds
max_interest_pct: 0.05  # Maximum proportion of interest income to total revenue
max_debt_ratio: 0.33    # Maximum proportion of total debt to total assets

# Halal Crypto definitions
halal_crypto:
  BTC/USDT:
    reason: "Digital gold"
    risk_level: medium
    utility_score: 0.9
  ETH/USDT:
    reason: "Smart contract platform enabling decentralized applications"
    risk_level: medium
    utility_score: 0.85
  ADA/USDT:
    reason: "Research-driven blockchain with academic backing and proof-of-stake"
    risk_level: low
    utility_score: 0.8

# Prohibited features
prohibited_features:
  PRIVACY: "Privacy coins facilitate illicit activity"
  LEVERAGE: "Excessive leverage amplifies risk and resembles gambling"
  DERIVATIVES: "Complex derivative products often embed interest or speculative elements"